services:
  nginx:
    build: .
    container_name: nginx
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      # - ./certs:/etc/nginx/certs
      - ./conf/snippets:/etc/nginx/snippets
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - frontend_net
      - internal_net

networks:
  frontend_net:
    driver: bridge
  internal_net:
    internal: true
